spring:
  datasource:
    url: jdbc:mysql://${DB_URL:localhost}:3306/SMonkey?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: limsaehyun
    password: @tmzlt123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}
        show_sql: ${SHOW_SQL:true}
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE